version: "2"
services:
  disk:
    container_name: disk
    image: debian:jessie
    volumes:
      - /etc/nginx:/etc/nginx
      - /etc/nginx:/usr/local/openresty/nginx/conf
      - /var/log/nginx:/var/log/nginx
      - /var/log/letsencrypt:/var/log/letsencrypt 
      - /var/log/php-fpm:/var/log/php-fpm
      - /var/log/nginx:/usr/local/openresty/nginx/logs
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run2:/var/run
      - /var/run2/nginx-cache/ngx_pagespeed:/var/cache/ngx_pagespeed 
      - /var/www:/var/www
      - ${HOME}:${HOME}
    networks:
      devkit:
          ipv4_address: 172.28.5.60
  php-fpm7:
    container_name: php7
    image: apiki/php7:1.0
    volumes_from:
      - disk
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
    networks:
      devkit:
          ipv4_address: 172.28.5.63
    extra_hosts:
      - "db:172.28.5.64"
    env_file: .env
  php-fpm6:
    container_name: php6
    image: apiki/php6:1.0
    volumes_from:
      - disk
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
    networks:
      devkit:
          ipv4_address: 172.28.5.62
    extra_hosts:
      - "db:172.28.5.64"
    env_file: .env
  webserver:
    container_name: webserver
    image: apiki/webserver:1.0
    volumes_from:
      - disk
    ports:
      - "80:80"
      - "443:443"
    networks:
      devkit:
          ipv4_address: 172.28.5.61
    env_file: .env
  mysql:
    container_name: mysql
    image: apiki/mysql:1.0
    volumes_from:
      - disk
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      devkit:
          ipv4_address: 172.28.5.64
    env_file: .env
  node:
    container_name: node
    image: apiki/node:1.0
    volumes_from:
      - disk
    networks:
      devkit:
          ipv4_address: 172.28.5.65
    env_file: .env
networks:
  devkit:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16
